# meta_product_name: "Krok"
# meta_title: "Krok - Your meal planner"
# meta_description: "Planning your meals and grocery shopping become easier with Krok! "
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@CombarelM"   # required for Twitter Cards

meta_product_name: "Krok"
meta_title: "Krok - My meal Organizer"
meta_description: "Organise better your meals and organizers"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
